services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    restart: always
    volumes:
      - ./backend:/app:cached
      - backend_node_modules:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - EXTERNAL_PORT=${EXTERNAL_PORT}
    ports:
      - "${EXTERNAL_PORT}:${PORT}"

volumes:
  backend_node_modules:
  db_data: